module.exports = [
    {
        nome: 'X Carne',
        descricao: 'Carne suculenta de 56g, mussarela derretida, presunto, tomate, orégano no pão macio.',
        preco: 10.00,
        foto: 'assets/x_carne.webp',
        categoria: 'burgers',
        ativo: 1,
        ordem: 1,
        qtd: 1,
        itemPromocao: 0,
        diasPromocao: '',
        descontoPromo: 1.00
    },
    {
        nome: 'X Picanha',
        descricao: 'Carne de picanha de 56g, presunto, mussarela e catupiry cremoso.',
        preco: 11.00,
        foto: 'assets/x_picanha.webp',
        categoria: 'burgers',
        ativo: 1,
        ordem: 2,
        qtd: 1,
        itemPromocao: 0,
        diasPromocao: '',
        descontoPromo: 1.00
    },
    {
        nome: 'Duplo Cheddar',
        descricao: 'Pão macio, duas carnes suculentas de 56g e cheddar delicioso.',
        preco: 10.00,
        foto: 'assets/duplo_cheddar.webp',
        categoria: 'burgers',
        ativo: 1,
        ordem: 3,
        qtd: 1,
        itemPromocao: 0,
        diasPromocao: '',
        descontoPromo: 1.00
    },
    {
        nome: 'Coxinha de Frango',
        descricao: 'Coxinha de frango cremosa de 100g, feita com massa artesanal de batata. Receita da casa.',
        preco: 9.00,
        foto: 'assets/coxinha_premium.webp',
        categoria: 'coxinha',
        ativo: 1,
        ordem: 4,
        qtd: 1,
        itemPromocao: 0,
        diasPromocao: '',
        descontoPromo: 1.00
    },
    {
        nome: 'Croissant Presunto e Queijo',
        descricao: 'O clássico folhado recheado com presunto fatiado e queijo derretido.',
        preco: 10.00,
        foto: 'assets/croissant_presunto_queijo_premium.webp',
        categoria: 'croissant',
        ativo: 1,
        ordem: 5,
        qtd: 1,
        itemPromocao: 0,
        diasPromocao: '',
        descontoPromo: 1.00
    },
    {
        nome: 'Lanche Natural de Frango',
        descricao: 'Lanche natural com frango desfiado, maionese, alface e cenoura ralada no pão de forma macio.',
        preco: 9.00,
        foto: 'assets/lanche_natural_frango.webp',
        categoria: 'lanches',
        ativo: 1,
        ordem: 6,
        qtd: 1,
        itemPromocao: 0,
        diasPromocao: '',
        descontoPromo: 1.00
    },
    {
        nome: 'Bauru de Presunto e Queijo',
        descricao: 'Clássico bauru com massa fofinha e recheio generoso de presunto e queijo derretido, temperado com um toque de orégano.',
        preco: 9.00,
        foto: 'assets/bauru_queijo_presunto.webp',
        categoria: 'salgados',
        ativo: 1,
        ordem: 7,
        qtd: 1,
        itemPromocao: 0,
        diasPromocao: '',
        descontoPromo: 1.00
    },
    {
        nome: 'X Bacon',
        descricao: 'Carne de 56g, bacon crocante, mussarela derretida e maionese da casa no pão macio.',
        preco: 10.00,
        foto: 'assets/x_bacon.webp',
        categoria: 'burgers',
        ativo: 1,
        ordem: 8,
        qtd: 1,
        itemPromocao: 0,
        diasPromocao: '',
        descontoPromo: 1.00
    },
    {
        nome: 'X AGS',
        descricao: 'Pão macio, duas carnes suculentas de 56g, tomate, presunto, queijo, requeijão, calabresa e bacon.',
        preco: 14.00,
        foto: 'assets/x_ags_premium.webp',
        categoria: 'burgers',
        ativo: 1,
        ordem: 9,
        qtd: 1,
        itemPromocao: 0,
        diasPromocao: '',
        descontoPromo: 1.00
    }
];